version: '3.8'
services:
  app:
    build: .
    depends_on:
      - postgres
    mem_limit: 8g
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    restart: unless-stopped
    networks:
      - network

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mystudylife
    ports:
      - "5499:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./postgres/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    networks:
      - network

  nginx:
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/dev/nginx.conf:/etc/nginx/nginx.conf/:ro
      - ./nginx/dev/certbot/www:/var/www/certbot/:ro
      # - ./nginx/dev/certbot/conf/:/etc/nginx/ssl/:ro
      - ./nginx/dev/certs/:/etc/nginx/ssl/:ro
    depends_on:
      - app
      - certbot
    networks:
      - network
  
  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/dev/certbot/www:/var/www/certbot/:rw
      - ./nginx/dev/certbot/conf:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    command: certonly --webroot --webroot-path=/var/www/certbot --email mladen@borneagency.com --agree-tos --no-eff-email --force-renewal -d admin.mystudylife.borne.io


volumes:
  db-data:
  node_modules:

networks:
  network: